# Generated by Django 2.1 on 2018-09-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("botany", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="bot", name="code_size", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="bot", name="is_from_beginner", field=models.NullBooleanField()
        ),
        migrations.AddField(
            model_name="bot", name="is_goldfish", field=models.NullBooleanField()
        ),
        migrations.AddField(
            model_name="bot", name="is_one_hit_wonder", field=models.NullBooleanField()
        ),
    ]
